### ISSUE TITLE
三星S10 Android10 无法打开无线热点

### ISSUE THREAD

**Issue by tangzeyu7** [eurigo/WiFiUtils#1]
## 错误
```java
java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    at com.eurigo.wifilib.WifiUtils.startTethering(WifiUtils.java:359)
    at com.eurigo.wifilib.WifiUtils.openAp(WifiUtils.java:225)
    at com.tzy.test.MainActivity.onCreate$lambda-2$lambda-0(MainActivity.kt:27)
    at com.tzy.test.MainActivity.lambda$S-DJN7XKojfLe9SmobBs5Rr7GI8(Unknown Source:0)
    at com.tzy.test.-$$Lambda$MainActivity$S-DJN7XKojfLe9SmobBs5Rr7GI8.onClick(Unknown Source:2)
    at android.view.View.performClick(View.java:7869)
    at android.widget.TextView.performClick(TextView.java:14958)
    at android.view.View.performClickInternal(View.java:7838)
    at android.view.View.access$3600(View.java:886)
    at android.view.View$PerformClick.run(View.java:29362)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8034)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: java.lang.SecurityException: ConnectivityService: Neither user 10264 nor current process has android.permission.TETHER_PRIVILEGED.
    at android.os.Parcel.createException(Parcel.java:2088)
    at android.os.Parcel.readException(Parcel.java:2056)
    at android.os.Parcel.readException(Parcel.java:2004)
    at android.net.IConnectivityManager$Stub$Proxy.startTethering(IConnectivityManager.java:3600)
    at android.net.ConnectivityManager.startTethering(ConnectivityManager.java:2871)
    at android.net.ConnectivityManager.startTethering(ConnectivityManager.java:2829)
	... 18 more
Caused by: android.os.RemoteException: Remote stack trace:
    at android.app.ContextImpl.enforce(ContextImpl.java:2002)
    at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2030)
    at android.net.ConnectivityManager.enforceTetherChangePermission(ConnectivityManager.java:2522)
    at com.android.server.ConnectivityService.startTethering(ConnectivityService.java:4946)
    at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:1512)
```
## 权限配置
```xml
    <uses-permission
        android:name="android.permission.WRITE_SETTINGS"
        tools:ignore="ProtectedPermissions" />

    <uses-permission android:name="android.permission.INTERNET" />

    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />

    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.TETHER_PRIVILEGED" />
```

## 其他信息

![image](https://user-images.githubusercontent.com/20296836/148036181-d5056d76-d4a3-466d-aec9-f57d9ce80131.png)
![image](https://user-images.githubusercontent.com/20296836/148036211-89abfe94-60b6-4762-83fd-3a2c0e5074a7.png)

三星S10 Android11是没问题的,其他品牌的Android10也是没问题的,需要更多的信息,我再补充.

**Comment by eurigo** [comment]
打开热点是使用反射方式实现的，根据报错信息应该是找不到反射方法，需要参考三星源码，能否提供手机具体型号？

**Comment by tangzeyu7** [comment]
> 打开热点是使用反射方式实现的，根据报错信息应该是找不到反射方法，需要参考三星源码，能否提供手机具体型号？

![8b2fd15edcaf2a2ee5c82648b6934e5](https://user-images.githubusercontent.com/20296836/153115693-5777cc0c-6e68-45bb-bb13-fea449dd775e.jpg)
![c4c94949f3823617931b736c4c4cab3](https://user-images.githubusercontent.com/20296836/153115748-f55ccbbf-7a65-4f19-8a69-d19bd831db57.jpg)

**Comment by tangzeyu7** [comment]
三星S10不论是美版还是日版(我手上只有这2个版本),只要是Android10,都有这个问题,

**Comment by eurigo** [comment]
暂未找到三星源码，也无实机，可以尝试在Manifest添加试试
```
    <uses-permission
        android:name="android.permission.TETHER_PRIVILEGED"
        tools:ignore="ProtectedPermissions" />
```
或者引导热点页面手动开启吧

**Comment by tangzeyu7** [comment]
> 暂未找到三星源码，也无实机，可以尝试在Manifest添加试试
> 
> ```
>     <uses-permission
>         android:name="android.permission.TETHER_PRIVILEGED"
>         tools:ignore="ProtectedPermissions" />
> ```
> 
> 或者引导热点页面手动开启吧

经测试在Manifest添加权限无效.
谢谢.
